import "dotenv/config";

const {
  POSTGRES_URI_DEV,
  POSTGRES_URI_PROD,
  SECRET_WORD,
  GMAIL_DIR,
  GMAIL_PASSWORD,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_KEY,
  CLOUDINARY_NAME,
  GLOBAL_PASSWORD,
} = process.env;

const PORT = process.env.PORT || 3000;
const NODE_ENV = process.env.NODE_ENV || "development";

export default {
  PORT,
  POSTGRES_URI_DEV,
  POSTGRES_URI_PROD,
  SECRET_WORD,
  GMAIL_DIR,
  GMAIL_PASSWORD,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_KEY,
  CLOUDINARY_NAME,
  GLOBAL_PASSWORD,
  NODE_ENV,
};
